### ISSUE TITLE
Error 500 when adding a camera model

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#278]
**Describe the bug**
```
Internal Server Error: /cameramodel/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 383, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 403, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1188, in full_clean
    self.clean()
  File "./schema/models.py", line 845, in clean
    if self.metering_modes is True:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 527, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 838, in __init__
    raise ValueError('"%r" needs to have a value for field "%s" before '
ValueError: "<CameraModel: Canon Canonflex>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

**Version of CameraHub**
0.4.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a camera model with at least one metering mode selected

**Expected behaviour**
It should work

**Comment by djjudas21** [comment]
**Workaround**: Add a new camera model with nothing set except the model name. Then edit the record to add the rest of the data.

**Comment by djjudas21** [comment]
Raised https://forum.djangoproject.com/t/valueerror-needs-to-have-a-value-for-field-id-before-this-many-to-many-relationship-can-be-used/1808/1

**Comment by djjudas21** [comment]
Depends on #280 so this can be tested against Postgres

**Comment by djjudas21** [comment]
This has not been directly addressed, however I cannot recreate the bug on v0.6.3 (now in production) so it must have been fixed as a side effect.

**Comment by djjudas21** [comment]
This is still occurring in 0.9.3:

```
Internal Server Error: /cameramodel/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 383, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 403, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1188, in full_clean
    self.clean()
  File "./schema/models.py", line 1439, in clean
    if self.metering_modes is True:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 527, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 838, in __init__
    raise ValueError('"%r" needs to have a value for field "%s" before '
ValueError: "<CameraModel: Canon Canonflex R2000>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

**Comment by djjudas21** [comment]
I'm confused by this. I have added the following overridden save method to `CameraModelForm`:

```py
def save(self, commit=True):
    form = super(CameraModelForm, self).save(commit=False)
    if commit:
        form.save(commit=False)
        form.save_m2m()
    return form
```

But this throws an error:

```
save() got an unexpected keyword argument 'commit' 
/home/jonathan/git/camerahub/schema/models.py in save, line 1397
```

Which is the overridden save method in `CameraModel`. I can't see any bugs with this; it just populates a slug field.

However I'm wondering if there's another bug somewhere because I don't seem to have m2m errors in any other model or form - only CameraModel.

**Comment by djjudas21** [comment]
Posted this for help https://stackoverflow.com/questions/61978224/models-and-modelforms-needs-to-have-a-value-for-field-id-before-this-many-to
