### ISSUE TITLE
Error 500 when registering a new user

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#451]
**Describe the bug**
After entering username and password to register a new user, browser returns error 500

Server log:
```
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_registration/views.py", line 52, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/django_registration/views.py", line 96, in form_valid
    return HttpResponseRedirect(self.get_success_url(self.register(form)))
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 41, in register
    new_user = self.create_inactive_user(form)
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 57, in create_inactive_user
    self.send_activation_email(new_user)
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 103, in send_activation_email
    user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 354, in email_user
    send_mail(subject, message, from_email, [self.email], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/site-packages/sendgrid_backend/mail.py", line 122, in send_messages
    resp = self.sg.client.mail.send.post(request_body=data)
  File "/usr/local/lib/python3.8/site-packages/python_http_client/client.py", line 262, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/python_http_client/client.py", line 178, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
```

**Version of CameraHub**
v0.10.5

**Comment by djjudas21** [comment]
Possibly an auth problem with Sendgrid?

**Comment by djjudas21** [comment]
Can't recreate this in dev

**Comment by djjudas21** [comment]
Previous error was due to the SendGrid API key being revoked. I've now replaced this but now getting the following error:

```
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_registration/views.py", line 52, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/django_registration/views.py", line 96, in form_valid
    return HttpResponseRedirect(self.get_success_url(self.register(form)))
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 41, in register
    new_user = self.create_inactive_user(form)
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 57, in create_inactive_user
    self.send_activation_email(new_user)
  File "/usr/local/lib/python3.8/site-packages/django_registration/backends/activation/views.py", line 103, in send_activation_email
    user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 354, in email_user
    send_mail(subject, message, from_email, [self.email], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/site-packages/sendgrid_backend/mail.py", line 122, in send_messages
    resp = self.sg.client.mail.send.post(request_body=data)
  File "/usr/local/lib/python3.8/site-packages/python_http_client/client.py", line 262, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/python_http_client/client.py", line 174, in _make_request
    return opener.open(request, timeout=timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again>
```

**Comment by djjudas21** [comment]
This is now fixed. Root cause was broken pod networking
