### ISSUE TITLE
Error 500 when viewing negative sizes

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#461]
**Describe the bug**
Error 500 when attempting to list negative sizes at https://camerahub.info/negativesize/

**Version of CameraHub**
v0.10.8

**Comment by djjudas21** [comment]
```
Internal Server Error: /negativesize/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "./schema/views.py", line 706, in get_context_data
    if self.get_object().history.all():
AttributeError: 'NegativeSizeList' object has no attribute 'get_object'
```
