### ISSUE TITLE
Crash on lensmodel list

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#659]
**Describe the bug**
```
2020-12-08T15:35:39.734279295Z stderr F Internal Server Error: /lensmodel/
2020-12-08T15:35:39.734325674Z stderr F Traceback (most recent call last):
2020-12-08T15:35:39.73433644Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-12-08T15:35:39.734343937Z stderr F     response = get_response(request)
2020-12-08T15:35:39.73435332Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
2020-12-08T15:35:39.734359813Z stderr F     response = self.process_exception_by_middleware(e, request)
2020-12-08T15:35:39.734366148Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
2020-12-08T15:35:39.734372548Z stderr F     response = response.render()
2020-12-08T15:35:39.734379419Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 106, in render
2020-12-08T15:35:39.734384921Z stderr F     self.content = self.rendered_content
2020-12-08T15:35:39.734396606Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
2020-12-08T15:35:39.73440364Z stderr F     content = template.render(context, self._request)
2020-12-08T15:35:39.734410121Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
2020-12-08T15:35:39.734415836Z stderr F     return self.template.render(context)
2020-12-08T15:35:39.734421536Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
2020-12-08T15:35:39.734428021Z stderr F     return self._render(context)
2020-12-08T15:35:39.734434138Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
2020-12-08T15:35:39.734440233Z stderr F     return self.nodelist.render(context)
2020-12-08T15:35:39.734446294Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734458668Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734473517Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734481002Z stderr F     return self.render(context)
2020-12-08T15:35:39.734489019Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
2020-12-08T15:35:39.7344955Z stderr F     return compiled_parent._render(context)
2020-12-08T15:35:39.734501823Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
2020-12-08T15:35:39.734507287Z stderr F     return self.nodelist.render(context)
2020-12-08T15:35:39.734512941Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734518978Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734524599Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734530584Z stderr F     return self.render(context)
2020-12-08T15:35:39.734536855Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
2020-12-08T15:35:39.734542805Z stderr F     result = block.nodelist.render(context)
2020-12-08T15:35:39.734548498Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734554496Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.73456034Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734566649Z stderr F     return self.render(context)
2020-12-08T15:35:39.734572483Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
2020-12-08T15:35:39.734578432Z stderr F     return nodelist.render(context)
2020-12-08T15:35:39.734584005Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734589862Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734595523Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734601381Z stderr F     return self.render(context)
2020-12-08T15:35:39.734607383Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
2020-12-08T15:35:39.734613408Z stderr F     return template.render(context={"table": table}, request=request)
2020-12-08T15:35:39.734619612Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
2020-12-08T15:35:39.734631264Z stderr F     return self.template.render(context)
2020-12-08T15:35:39.734637103Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
2020-12-08T15:35:39.734642851Z stderr F     return self._render(context)
2020-12-08T15:35:39.734650459Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
2020-12-08T15:35:39.734656785Z stderr F     return self.nodelist.render(context)
2020-12-08T15:35:39.73466291Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734671161Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734677008Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734682623Z stderr F     return self.render(context)
2020-12-08T15:35:39.734688305Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
2020-12-08T15:35:39.734694403Z stderr F     result = self.nodelist.render(context)
2020-12-08T15:35:39.734700104Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734710836Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734717218Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734772159Z stderr F     return self.render(context)
2020-12-08T15:35:39.734787455Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
2020-12-08T15:35:39.734795144Z stderr F     result = self.nodelist.render(context)
2020-12-08T15:35:39.734823766Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734834012Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734840162Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734846238Z stderr F     return self.render(context)
2020-12-08T15:35:39.734866739Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
2020-12-08T15:35:39.734873887Z stderr F     result = self.nodelist.render(context)
2020-12-08T15:35:39.734887293Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734893553Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.734900502Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734906721Z stderr F     return self.render(context)
2020-12-08T15:35:39.734926184Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
2020-12-08T15:35:39.734933058Z stderr F     nodelist.append(node.render_annotated(context))
2020-12-08T15:35:39.734939146Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.734946622Z stderr F     return self.render(context)
2020-12-08T15:35:39.734952517Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
2020-12-08T15:35:39.734958574Z stderr F     result = self.nodelist.render(context)
2020-12-08T15:35:39.734988624Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-12-08T15:35:39.734996631Z stderr F     bit = node.render_annotated(context)
2020-12-08T15:35:39.735002492Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-12-08T15:35:39.735008367Z stderr F     return self.render(context)
2020-12-08T15:35:39.735014187Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 165, in render
2020-12-08T15:35:39.735050236Z stderr F     values = list(values)
2020-12-08T15:35:39.735064998Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/rows.py", line 244, in items
2020-12-08T15:35:39.735072655Z stderr F     column.current_value = self.get_cell(column.name)
2020-12-08T15:35:39.735078582Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/rows.py", line 197, in get_cell
2020-12-08T15:35:39.735084258Z stderr F     return self._get_and_render_with(
2020-12-08T15:35:39.735091864Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/rows.py", line 173, in _get_and_render_with
2020-12-08T15:35:39.735118271Z stderr F     return render_func(bound_column, value)
2020-12-08T15:35:39.73512442Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/rows.py", line 206, in _call_render
2020-12-08T15:35:39.735130367Z stderr F     content = call_with_appropriate(bound_column.render, render_kwargs)
2020-12-08T15:35:39.735136082Z stderr F   File "/usr/local/lib/python3.8/site-packages/django_tables2/utils.py", line 572, in call_with_appropriate
2020-12-08T15:35:39.735141607Z stderr F     return fn(**kwargs)
2020-12-08T15:35:39.735147681Z stderr F   File "./schema/tables.py", line 289, in render_model
2020-12-08T15:35:39.735177362Z stderr F     mystr = format_html("<a href=\"{}\">{} {}</a>", reverse(
2020-12-08T15:35:39.735184496Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/urls/base.py", line 90, in reverse
2020-12-08T15:35:39.735191143Z stderr F     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
2020-12-08T15:35:39.735196663Z stderr F   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
2020-12-08T15:35:39.735202271Z stderr F     raise NoReverseMatch(msg)
2020-12-08T15:35:39.735229027Z stderr F django.urls.exceptions.NoReverseMatch: Reverse for 'lensmodel-detail' not found. 'lensmodel-detail' is not a valid view function or pattern name.
```

**Version of CameraHub**
0.24.2

**Comment by djjudas21** [comment]
This was already fixed in a948207e
