### ISSUE TITLE
Error 500 on lensmodel list

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#847]
**Describe the bug**
Error 500 in browser when attempting to visit https://camerahub.info/lensmodel/

```
Internal Server Error: /lensmodel/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column schema_lensmodel.purpose does not exist
LINE 1: ...."disambiguation", "schema_lensmodel"."mount_id", "schema_le...
                                                             ^
```

**Comment by djjudas21** [comment]
Can't recreate this on dev @ 2ff9016d1f4ce4b3e9f8fc042e2cd0f2b65c5aa9

**Comment by djjudas21** [comment]
```
Internal Server Error: /lensmodel/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
  File "/camerahub/./schema/views.py", line 592, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/camerahub/./schema/views.py", line 71, in get_context_data
    context = super().get_context_data()
  File "/usr/local/lib/python3.9/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
  File "/usr/local/lib/python3.9/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
  File "/usr/local/lib/python3.9/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
  File "/usr/local/lib/python3.9/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/usr/local/lib/python3.9/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 2016, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'focal_length' into field. Choices are: accessory, aperture_blades, autofocus, closest_focus, coating, diagram, diagram_attribution, diagram_attribution_link, diameter, disambiguation, discontinued, elements, filter_thread, groups, hood, id, image, image_attribution, image_attribution_link, image_circle, introduced, length, lens, lens_type, link, magnification, manufacturer, manufacturer_id, max_aperture, max_focal_length, min_aperture, min_focal_length, model, mount, mount_id, negative_size, negative_size_id, nominal_max_angle_diag, nominal_min_angle_diag, notes, perspective_control, purpose, ratings, shutter_model, slug, tagged_items, tags, weight, zoom, zoom_ratio
```

**Comment by djjudas21** [comment]
At the moment I can't see what triggers this error, but for me I'm able to create and view Lens Models and Lenses with variable focal lengths, fixed focal lengths, and null focal lengths

**Comment by djjudas21** [comment]
Looks like a dupe of #801
