### ISSUE TITLE
decimal.InvalidOperation

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#884]
This is triggered when hitting the EXIF API for some scans. I have a hunch it could be with the way Rationals are presented from Decimals but there's not much to go on here

**Describe the bug**
```
Internal Server Error: /api/exif/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1081, in to_representation
    quantized = self.quantize(value)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1100, in quantize
    return value.quantize(
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
[pid: 8|app: 0|req: 12989/18660] 10.1.71.246 () {48 vars in 792 bytes} [Fri Apr 28 17:53:31 2023] GET /api/exif/?uuid=64dc9f01-8580-4a1a-8d3c-bc0763a6dd8b => generated 897 bytes in 205 msecs (HTTP/1.1 500) 6 headers in 199 bytes (1 switches on core 3)
```

**Version of CameraHub**
0.36.x

**Comment by djjudas21** [comment]
Affected negs:
* https://camerahub.info/negative/118.15
* https://camerahub.info/negative/123.13
* https://camerahub.info/negative/149.13
* https://camerahub.info/negative/180.21

All the negs I've checked so far have a shutter speed of 1". So it looks like a problem with handling shutter speeds that don't conform to the 1/60 format.
