### ISSUE TITLE
Permission denied: '/camerahub/media/health_check_storage_test'

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#922]
**Describe the bug**
This error occurs since running camerahub-dev on CephFS instead of TrueNAS

```
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55f6f14bd940 pid: 7 (default app)
unavailable: Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/health_check/storage/backends.py", line 63, in check_status
    file_name = self.check_save(file_name, file_content)
  File "/usr/local/lib/python3.10/site-packages/health_check/storage/backends.py", line 42, in check_save
    file_name = storage.save(file_name, ContentFile(content=file_content))
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 54, in save
    name = self._save(name, content)
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 260, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/camerahub/media/health_check_storage_test'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/usr/local/lib/python3.10/site-packages/health_check/storage/backends.py", line 67, in check_status
    raise ServiceUnavailable("Unknown exception") from e
health_check.exceptions.ServiceUnavailable: unavailable: Unknown exception
Internal Server Error: /health/
[pid: 8|app: 0|req: 1/1] 192.168.0.58 () {30 vars in 363 bytes} [Sat Aug 26 21:38:53 2023] GET /health/ => generated 1767 bytes in 527 msecs (HTTP/1.1 500) 7 headers in 298 bytes (1 switches on core 0)
```

**Version of CameraHub**
Latest

**Comment by djjudas21** [comment]
Reported upstream as https://github.com/revsys/django-health-check/issues/376
